name: tif_assignment_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # responsive_framework: ^0.2.0
  device_preview: ^1.1.0
  flutter_screenutil: ^5.7.0
  # api handling
  dio: ^5.0.1
  # service locator & for creating singletons
  get_it: ^7.2.0
  # state management
  flutter_bloc: ^8.1.2
  # adding value equality
  equatable: ^2.0.5
  # functional programming uses
  dartz: ^0.10.1
  # checking network connectivity
  internet_connection_checker: ^1.0.0+1
  date_time_format: ^2.0.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
